BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ROOM" (
	"ROOM_ID"	INTEGER,
	"FLOOR_NUMBER"	INTEGER NOT NULL,
	"SEAT_CAPACITY"	INTEGER NOT NULL,
	PRIMARY KEY("ROOM_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ATTENDEE" (
	"ATTENDEE_ID"	INTEGER,
	"FIRST_NAME"	VARCHAR(30) NOT NULL,
	"LAST_NAME"	VARCHAR(30) NOT NULL,
	"PHONE"	INTEGER,
	"EMAIL"	VARCHAR(30),
	"VIP"	BOOLEAN DEFAULT (1),
	PRIMARY KEY("ATTENDEE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PRESENTATION_ATTENDANCE" (
	"TICKET_ID"	INTEGER,
	"PRESENTATION_ID"	INTEGER,
	"ATTENDEE_ID"	INTEGER,
	PRIMARY KEY("TICKET_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "COMPANY" (
	"COMPANY_ID"	INTEGER,
	"NAME"	VARCHAR(30) NOT NULL,
	"DESCRIPTION"	VARCHAR(60),
	"PRIMARY_CONTACT_ID"	INTEGER NOT NULL,
	PRIMARY KEY("COMPANY_ID" AUTOINCREMENT),
	FOREIGN KEY("PRIMARY_CONTACT_ID") REFERENCES "ATTENDEE"("ATTENDEE_ID")
);
CREATE TABLE IF NOT EXISTS "PRESENTATION" (
	"PRESENTATION_ID"	INTEGER,
	"BOOKED_COMPANY_ID"	INTEGER NOT NULL,
	"BOOKED_ROOM_ID"	INTEGER NOT NULL,
	"START_TIME"	TIME,
	"END_TIME"	TIME,
	PRIMARY KEY("PRESENTATION_ID" AUTOINCREMENT),
	FOREIGN KEY("BOOKED_ROOM_ID") REFERENCES "COMPANY"("COMPANY_ID"),
	FOREIGN KEY("BOOKED_COMPANY_ID") REFERENCES "COMPANY"("COMPANY_ID")
);
INSERT INTO "ROOM" VALUES (1,9,80);
INSERT INTO "ROOM" VALUES (2,10,110);
INSERT INTO "ATTENDEE" VALUES (1,'THOMAS','NIELD',NULL,NULL,0);
INSERT INTO "ATTENDEE" VALUES (2,'JON','SKEETER',4802185842,'JOHN.SKEETER@REX.NET',1);
INSERT INTO "ATTENDEE" VALUES (3,'SAM','SCALA',2156783401,'SAM.SCALA@GMAIL.COM',1);
INSERT INTO "ATTENDEE" VALUES (4,'BRITTANY','FISHER',5932857296,'BRITTANY.FISHER@OUTLOOK.COM',1);
CREATE VIEW PRESENTATION_VW AS SELECT COMPANY.NAME AS BOOKED_COMPANY, ROOM.ROOM_ID AS ROOM_NUMBER, ROOM.FLOOR_NUMBER AS FLOOR, ROOM.SEAT_CAPACITY AS SEATS, START_TIME, END_TIME FROM PRESENTATION INNER JOIN COMPANY ON PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID INNER JOIN ROOM ON PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;
COMMIT;
